version: '2'
services:
    db:
        image: postgres:9.6.1-alpine
        ports:
            - "${DB_PORT}:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata-ldv02:/var/lib/postgresql/data
    php:
        build: ./php
        links:
            - db
        expose:
            - "9000"
        volumes:
            - .:/usr/share/nginx/html
    nginx:
        build: ./nginx
        volumes:
            - .:/usr/share/nginx/html
        links:
            - php
        ports:
            - "${DOCKER_NGINX_PORT}:80"
#Não é necessário para rodar no linux.
#Caso seja configurado, o volume deve ser criado antes do up: docker volume create --name=pgdata-ldv02
volumes:
    pgdata-ldv02:
        external: true
